// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AllMsg.proto

public final class AllMsg {
  private AllMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <pre>
     *登录 | 登出
     * </pre>
     *
     * <code>.CS_Login_Req loginReq = 2;</code>
     */
    boolean hasLoginReq();
    /**
     * <pre>
     *登录 | 登出
     * </pre>
     *
     * <code>.CS_Login_Req loginReq = 2;</code>
     */
    Login.CS_Login_Req getLoginReq();
    /**
     * <pre>
     *登录 | 登出
     * </pre>
     *
     * <code>.CS_Login_Req loginReq = 2;</code>
     */
    Login.CS_Login_ReqOrBuilder getLoginReqOrBuilder();

    /**
     * <code>.SC_Login_Res loginRes = 3;</code>
     */
    boolean hasLoginRes();
    /**
     * <code>.SC_Login_Res loginRes = 3;</code>
     */
    Login.SC_Login_Res getLoginRes();
    /**
     * <code>.SC_Login_Res loginRes = 3;</code>
     */
    Login.SC_Login_ResOrBuilder getLoginResOrBuilder();

    /**
     * <code>.CS_Logout_Req logoutReq = 4;</code>
     */
    boolean hasLogoutReq();
    /**
     * <code>.CS_Logout_Req logoutReq = 4;</code>
     */
    Login.CS_Logout_Req getLogoutReq();
    /**
     * <code>.CS_Logout_Req logoutReq = 4;</code>
     */
    Login.CS_Logout_ReqOrBuilder getLogoutReqOrBuilder();

    /**
     * <code>.SC_Logout_Res logoutRes = 5;</code>
     */
    boolean hasLogoutRes();
    /**
     * <code>.SC_Logout_Res logoutRes = 5;</code>
     */
    Login.SC_Logout_Res getLogoutRes();
    /**
     * <code>.SC_Logout_Res logoutRes = 5;</code>
     */
    Login.SC_Logout_ResOrBuilder getLogoutResOrBuilder();

    public AllMsg.NetMsg.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code NetMsg}
   */
  public  static final class NetMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NetMsg)
      NetMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetMsg.newBuilder() to construct.
    private NetMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetMsg() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NetMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              Login.CS_Login_Req.Builder subBuilder = null;
              if (dataCase_ == 2) {
                subBuilder = ((Login.CS_Login_Req) data_).toBuilder();
              }
              data_ =
                  input.readMessage(Login.CS_Login_Req.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Login.CS_Login_Req) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 2;
              break;
            }
            case 26: {
              Login.SC_Login_Res.Builder subBuilder = null;
              if (dataCase_ == 3) {
                subBuilder = ((Login.SC_Login_Res) data_).toBuilder();
              }
              data_ =
                  input.readMessage(Login.SC_Login_Res.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Login.SC_Login_Res) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 3;
              break;
            }
            case 34: {
              Login.CS_Logout_Req.Builder subBuilder = null;
              if (dataCase_ == 4) {
                subBuilder = ((Login.CS_Logout_Req) data_).toBuilder();
              }
              data_ =
                  input.readMessage(Login.CS_Logout_Req.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Login.CS_Logout_Req) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 4;
              break;
            }
            case 42: {
              Login.SC_Logout_Res.Builder subBuilder = null;
              if (dataCase_ == 5) {
                subBuilder = ((Login.SC_Logout_Res) data_).toBuilder();
              }
              data_ =
                  input.readMessage(Login.SC_Logout_Res.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Login.SC_Logout_Res) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 5;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AllMsg.internal_static_NetMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AllMsg.internal_static_NetMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AllMsg.NetMsg.class, AllMsg.NetMsg.Builder.class);
    }

    private int dataCase_ = 0;
    private java.lang.Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite {
      LOGINREQ(2),
      LOGINRES(3),
      LOGOUTREQ(4),
      LOGOUTRES(5),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 2: return LOGINREQ;
          case 3: return LOGINRES;
          case 4: return LOGOUTREQ;
          case 5: return LOGOUTRES;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int LOGINREQ_FIELD_NUMBER = 2;
    /**
     * <pre>
     *登录 | 登出
     * </pre>
     *
     * <code>.CS_Login_Req loginReq = 2;</code>
     */
    public boolean hasLoginReq() {
      return dataCase_ == 2;
    }
    /**
     * <pre>
     *登录 | 登出
     * </pre>
     *
     * <code>.CS_Login_Req loginReq = 2;</code>
     */
    public Login.CS_Login_Req getLoginReq() {
      if (dataCase_ == 2) {
         return (Login.CS_Login_Req) data_;
      }
      return Login.CS_Login_Req.getDefaultInstance();
    }
    /**
     * <pre>
     *登录 | 登出
     * </pre>
     *
     * <code>.CS_Login_Req loginReq = 2;</code>
     */
    public Login.CS_Login_ReqOrBuilder getLoginReqOrBuilder() {
      if (dataCase_ == 2) {
         return (Login.CS_Login_Req) data_;
      }
      return Login.CS_Login_Req.getDefaultInstance();
    }

    public static final int LOGINRES_FIELD_NUMBER = 3;
    /**
     * <code>.SC_Login_Res loginRes = 3;</code>
     */
    public boolean hasLoginRes() {
      return dataCase_ == 3;
    }
    /**
     * <code>.SC_Login_Res loginRes = 3;</code>
     */
    public Login.SC_Login_Res getLoginRes() {
      if (dataCase_ == 3) {
         return (Login.SC_Login_Res) data_;
      }
      return Login.SC_Login_Res.getDefaultInstance();
    }
    /**
     * <code>.SC_Login_Res loginRes = 3;</code>
     */
    public Login.SC_Login_ResOrBuilder getLoginResOrBuilder() {
      if (dataCase_ == 3) {
         return (Login.SC_Login_Res) data_;
      }
      return Login.SC_Login_Res.getDefaultInstance();
    }

    public static final int LOGOUTREQ_FIELD_NUMBER = 4;
    /**
     * <code>.CS_Logout_Req logoutReq = 4;</code>
     */
    public boolean hasLogoutReq() {
      return dataCase_ == 4;
    }
    /**
     * <code>.CS_Logout_Req logoutReq = 4;</code>
     */
    public Login.CS_Logout_Req getLogoutReq() {
      if (dataCase_ == 4) {
         return (Login.CS_Logout_Req) data_;
      }
      return Login.CS_Logout_Req.getDefaultInstance();
    }
    /**
     * <code>.CS_Logout_Req logoutReq = 4;</code>
     */
    public Login.CS_Logout_ReqOrBuilder getLogoutReqOrBuilder() {
      if (dataCase_ == 4) {
         return (Login.CS_Logout_Req) data_;
      }
      return Login.CS_Logout_Req.getDefaultInstance();
    }

    public static final int LOGOUTRES_FIELD_NUMBER = 5;
    /**
     * <code>.SC_Logout_Res logoutRes = 5;</code>
     */
    public boolean hasLogoutRes() {
      return dataCase_ == 5;
    }
    /**
     * <code>.SC_Logout_Res logoutRes = 5;</code>
     */
    public Login.SC_Logout_Res getLogoutRes() {
      if (dataCase_ == 5) {
         return (Login.SC_Logout_Res) data_;
      }
      return Login.SC_Logout_Res.getDefaultInstance();
    }
    /**
     * <code>.SC_Logout_Res logoutRes = 5;</code>
     */
    public Login.SC_Logout_ResOrBuilder getLogoutResOrBuilder() {
      if (dataCase_ == 5) {
         return (Login.SC_Logout_Res) data_;
      }
      return Login.SC_Logout_Res.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (dataCase_ == 2) {
        output.writeMessage(2, (Login.CS_Login_Req) data_);
      }
      if (dataCase_ == 3) {
        output.writeMessage(3, (Login.SC_Login_Res) data_);
      }
      if (dataCase_ == 4) {
        output.writeMessage(4, (Login.CS_Logout_Req) data_);
      }
      if (dataCase_ == 5) {
        output.writeMessage(5, (Login.SC_Logout_Res) data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (dataCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Login.CS_Login_Req) data_);
      }
      if (dataCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Login.SC_Login_Res) data_);
      }
      if (dataCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (Login.CS_Logout_Req) data_);
      }
      if (dataCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (Login.SC_Logout_Res) data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AllMsg.NetMsg)) {
        return super.equals(obj);
      }
      AllMsg.NetMsg other = (AllMsg.NetMsg) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getDataCase().equals(other.getDataCase())) return false;
      switch (dataCase_) {
        case 2:
          if (!getLoginReq()
              .equals(other.getLoginReq())) return false;
          break;
        case 3:
          if (!getLoginRes()
              .equals(other.getLoginRes())) return false;
          break;
        case 4:
          if (!getLogoutReq()
              .equals(other.getLogoutReq())) return false;
          break;
        case 5:
          if (!getLogoutRes()
              .equals(other.getLogoutRes())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      switch (dataCase_) {
        case 2:
          hash = (37 * hash) + LOGINREQ_FIELD_NUMBER;
          hash = (53 * hash) + getLoginReq().hashCode();
          break;
        case 3:
          hash = (37 * hash) + LOGINRES_FIELD_NUMBER;
          hash = (53 * hash) + getLoginRes().hashCode();
          break;
        case 4:
          hash = (37 * hash) + LOGOUTREQ_FIELD_NUMBER;
          hash = (53 * hash) + getLogoutReq().hashCode();
          break;
        case 5:
          hash = (37 * hash) + LOGOUTRES_FIELD_NUMBER;
          hash = (53 * hash) + getLogoutRes().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AllMsg.NetMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AllMsg.NetMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AllMsg.NetMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AllMsg.NetMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AllMsg.NetMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AllMsg.NetMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AllMsg.NetMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AllMsg.NetMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AllMsg.NetMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AllMsg.NetMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AllMsg.NetMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AllMsg.NetMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AllMsg.NetMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetMsg)
        AllMsg.NetMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AllMsg.internal_static_NetMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AllMsg.internal_static_NetMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AllMsg.NetMsg.class, AllMsg.NetMsg.Builder.class);
      }

      // Construct using AllMsg.NetMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AllMsg.internal_static_NetMsg_descriptor;
      }

      @java.lang.Override
      public AllMsg.NetMsg getDefaultInstanceForType() {
        return AllMsg.NetMsg.getDefaultInstance();
      }

      @java.lang.Override
      public AllMsg.NetMsg build() {
        AllMsg.NetMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AllMsg.NetMsg buildPartial() {
        AllMsg.NetMsg result = new AllMsg.NetMsg(this);
        result.code_ = code_;
        if (dataCase_ == 2) {
          if (loginReqBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = loginReqBuilder_.build();
          }
        }
        if (dataCase_ == 3) {
          if (loginResBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = loginResBuilder_.build();
          }
        }
        if (dataCase_ == 4) {
          if (logoutReqBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = logoutReqBuilder_.build();
          }
        }
        if (dataCase_ == 5) {
          if (logoutResBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = logoutResBuilder_.build();
          }
        }
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AllMsg.NetMsg) {
          return mergeFrom((AllMsg.NetMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AllMsg.NetMsg other) {
        if (other == AllMsg.NetMsg.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        switch (other.getDataCase()) {
          case LOGINREQ: {
            mergeLoginReq(other.getLoginReq());
            break;
          }
          case LOGINRES: {
            mergeLoginRes(other.getLoginRes());
            break;
          }
          case LOGOUTREQ: {
            mergeLogoutReq(other.getLogoutReq());
            break;
          }
          case LOGOUTRES: {
            mergeLogoutRes(other.getLogoutRes());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AllMsg.NetMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AllMsg.NetMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataCase_ = 0;
      private java.lang.Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Login.CS_Login_Req, Login.CS_Login_Req.Builder, Login.CS_Login_ReqOrBuilder> loginReqBuilder_;
      /**
       * <pre>
       *登录 | 登出
       * </pre>
       *
       * <code>.CS_Login_Req loginReq = 2;</code>
       */
      public boolean hasLoginReq() {
        return dataCase_ == 2;
      }
      /**
       * <pre>
       *登录 | 登出
       * </pre>
       *
       * <code>.CS_Login_Req loginReq = 2;</code>
       */
      public Login.CS_Login_Req getLoginReq() {
        if (loginReqBuilder_ == null) {
          if (dataCase_ == 2) {
            return (Login.CS_Login_Req) data_;
          }
          return Login.CS_Login_Req.getDefaultInstance();
        } else {
          if (dataCase_ == 2) {
            return loginReqBuilder_.getMessage();
          }
          return Login.CS_Login_Req.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *登录 | 登出
       * </pre>
       *
       * <code>.CS_Login_Req loginReq = 2;</code>
       */
      public Builder setLoginReq(Login.CS_Login_Req value) {
        if (loginReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          loginReqBuilder_.setMessage(value);
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <pre>
       *登录 | 登出
       * </pre>
       *
       * <code>.CS_Login_Req loginReq = 2;</code>
       */
      public Builder setLoginReq(
          Login.CS_Login_Req.Builder builderForValue) {
        if (loginReqBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          loginReqBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <pre>
       *登录 | 登出
       * </pre>
       *
       * <code>.CS_Login_Req loginReq = 2;</code>
       */
      public Builder mergeLoginReq(Login.CS_Login_Req value) {
        if (loginReqBuilder_ == null) {
          if (dataCase_ == 2 &&
              data_ != Login.CS_Login_Req.getDefaultInstance()) {
            data_ = Login.CS_Login_Req.newBuilder((Login.CS_Login_Req) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 2) {
            loginReqBuilder_.mergeFrom(value);
          }
          loginReqBuilder_.setMessage(value);
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <pre>
       *登录 | 登出
       * </pre>
       *
       * <code>.CS_Login_Req loginReq = 2;</code>
       */
      public Builder clearLoginReq() {
        if (loginReqBuilder_ == null) {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
          }
          loginReqBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *登录 | 登出
       * </pre>
       *
       * <code>.CS_Login_Req loginReq = 2;</code>
       */
      public Login.CS_Login_Req.Builder getLoginReqBuilder() {
        return getLoginReqFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *登录 | 登出
       * </pre>
       *
       * <code>.CS_Login_Req loginReq = 2;</code>
       */
      public Login.CS_Login_ReqOrBuilder getLoginReqOrBuilder() {
        if ((dataCase_ == 2) && (loginReqBuilder_ != null)) {
          return loginReqBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 2) {
            return (Login.CS_Login_Req) data_;
          }
          return Login.CS_Login_Req.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *登录 | 登出
       * </pre>
       *
       * <code>.CS_Login_Req loginReq = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Login.CS_Login_Req, Login.CS_Login_Req.Builder, Login.CS_Login_ReqOrBuilder> 
          getLoginReqFieldBuilder() {
        if (loginReqBuilder_ == null) {
          if (!(dataCase_ == 2)) {
            data_ = Login.CS_Login_Req.getDefaultInstance();
          }
          loginReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Login.CS_Login_Req, Login.CS_Login_Req.Builder, Login.CS_Login_ReqOrBuilder>(
                  (Login.CS_Login_Req) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 2;
        onChanged();;
        return loginReqBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Login.SC_Login_Res, Login.SC_Login_Res.Builder, Login.SC_Login_ResOrBuilder> loginResBuilder_;
      /**
       * <code>.SC_Login_Res loginRes = 3;</code>
       */
      public boolean hasLoginRes() {
        return dataCase_ == 3;
      }
      /**
       * <code>.SC_Login_Res loginRes = 3;</code>
       */
      public Login.SC_Login_Res getLoginRes() {
        if (loginResBuilder_ == null) {
          if (dataCase_ == 3) {
            return (Login.SC_Login_Res) data_;
          }
          return Login.SC_Login_Res.getDefaultInstance();
        } else {
          if (dataCase_ == 3) {
            return loginResBuilder_.getMessage();
          }
          return Login.SC_Login_Res.getDefaultInstance();
        }
      }
      /**
       * <code>.SC_Login_Res loginRes = 3;</code>
       */
      public Builder setLoginRes(Login.SC_Login_Res value) {
        if (loginResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          loginResBuilder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.SC_Login_Res loginRes = 3;</code>
       */
      public Builder setLoginRes(
          Login.SC_Login_Res.Builder builderForValue) {
        if (loginResBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          loginResBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.SC_Login_Res loginRes = 3;</code>
       */
      public Builder mergeLoginRes(Login.SC_Login_Res value) {
        if (loginResBuilder_ == null) {
          if (dataCase_ == 3 &&
              data_ != Login.SC_Login_Res.getDefaultInstance()) {
            data_ = Login.SC_Login_Res.newBuilder((Login.SC_Login_Res) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 3) {
            loginResBuilder_.mergeFrom(value);
          }
          loginResBuilder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.SC_Login_Res loginRes = 3;</code>
       */
      public Builder clearLoginRes() {
        if (loginResBuilder_ == null) {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
          }
          loginResBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.SC_Login_Res loginRes = 3;</code>
       */
      public Login.SC_Login_Res.Builder getLoginResBuilder() {
        return getLoginResFieldBuilder().getBuilder();
      }
      /**
       * <code>.SC_Login_Res loginRes = 3;</code>
       */
      public Login.SC_Login_ResOrBuilder getLoginResOrBuilder() {
        if ((dataCase_ == 3) && (loginResBuilder_ != null)) {
          return loginResBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 3) {
            return (Login.SC_Login_Res) data_;
          }
          return Login.SC_Login_Res.getDefaultInstance();
        }
      }
      /**
       * <code>.SC_Login_Res loginRes = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Login.SC_Login_Res, Login.SC_Login_Res.Builder, Login.SC_Login_ResOrBuilder> 
          getLoginResFieldBuilder() {
        if (loginResBuilder_ == null) {
          if (!(dataCase_ == 3)) {
            data_ = Login.SC_Login_Res.getDefaultInstance();
          }
          loginResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Login.SC_Login_Res, Login.SC_Login_Res.Builder, Login.SC_Login_ResOrBuilder>(
                  (Login.SC_Login_Res) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 3;
        onChanged();;
        return loginResBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Login.CS_Logout_Req, Login.CS_Logout_Req.Builder, Login.CS_Logout_ReqOrBuilder> logoutReqBuilder_;
      /**
       * <code>.CS_Logout_Req logoutReq = 4;</code>
       */
      public boolean hasLogoutReq() {
        return dataCase_ == 4;
      }
      /**
       * <code>.CS_Logout_Req logoutReq = 4;</code>
       */
      public Login.CS_Logout_Req getLogoutReq() {
        if (logoutReqBuilder_ == null) {
          if (dataCase_ == 4) {
            return (Login.CS_Logout_Req) data_;
          }
          return Login.CS_Logout_Req.getDefaultInstance();
        } else {
          if (dataCase_ == 4) {
            return logoutReqBuilder_.getMessage();
          }
          return Login.CS_Logout_Req.getDefaultInstance();
        }
      }
      /**
       * <code>.CS_Logout_Req logoutReq = 4;</code>
       */
      public Builder setLogoutReq(Login.CS_Logout_Req value) {
        if (logoutReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          logoutReqBuilder_.setMessage(value);
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <code>.CS_Logout_Req logoutReq = 4;</code>
       */
      public Builder setLogoutReq(
          Login.CS_Logout_Req.Builder builderForValue) {
        if (logoutReqBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          logoutReqBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <code>.CS_Logout_Req logoutReq = 4;</code>
       */
      public Builder mergeLogoutReq(Login.CS_Logout_Req value) {
        if (logoutReqBuilder_ == null) {
          if (dataCase_ == 4 &&
              data_ != Login.CS_Logout_Req.getDefaultInstance()) {
            data_ = Login.CS_Logout_Req.newBuilder((Login.CS_Logout_Req) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 4) {
            logoutReqBuilder_.mergeFrom(value);
          }
          logoutReqBuilder_.setMessage(value);
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <code>.CS_Logout_Req logoutReq = 4;</code>
       */
      public Builder clearLogoutReq() {
        if (logoutReqBuilder_ == null) {
          if (dataCase_ == 4) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 4) {
            dataCase_ = 0;
            data_ = null;
          }
          logoutReqBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.CS_Logout_Req logoutReq = 4;</code>
       */
      public Login.CS_Logout_Req.Builder getLogoutReqBuilder() {
        return getLogoutReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.CS_Logout_Req logoutReq = 4;</code>
       */
      public Login.CS_Logout_ReqOrBuilder getLogoutReqOrBuilder() {
        if ((dataCase_ == 4) && (logoutReqBuilder_ != null)) {
          return logoutReqBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 4) {
            return (Login.CS_Logout_Req) data_;
          }
          return Login.CS_Logout_Req.getDefaultInstance();
        }
      }
      /**
       * <code>.CS_Logout_Req logoutReq = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Login.CS_Logout_Req, Login.CS_Logout_Req.Builder, Login.CS_Logout_ReqOrBuilder> 
          getLogoutReqFieldBuilder() {
        if (logoutReqBuilder_ == null) {
          if (!(dataCase_ == 4)) {
            data_ = Login.CS_Logout_Req.getDefaultInstance();
          }
          logoutReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Login.CS_Logout_Req, Login.CS_Logout_Req.Builder, Login.CS_Logout_ReqOrBuilder>(
                  (Login.CS_Logout_Req) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 4;
        onChanged();;
        return logoutReqBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Login.SC_Logout_Res, Login.SC_Logout_Res.Builder, Login.SC_Logout_ResOrBuilder> logoutResBuilder_;
      /**
       * <code>.SC_Logout_Res logoutRes = 5;</code>
       */
      public boolean hasLogoutRes() {
        return dataCase_ == 5;
      }
      /**
       * <code>.SC_Logout_Res logoutRes = 5;</code>
       */
      public Login.SC_Logout_Res getLogoutRes() {
        if (logoutResBuilder_ == null) {
          if (dataCase_ == 5) {
            return (Login.SC_Logout_Res) data_;
          }
          return Login.SC_Logout_Res.getDefaultInstance();
        } else {
          if (dataCase_ == 5) {
            return logoutResBuilder_.getMessage();
          }
          return Login.SC_Logout_Res.getDefaultInstance();
        }
      }
      /**
       * <code>.SC_Logout_Res logoutRes = 5;</code>
       */
      public Builder setLogoutRes(Login.SC_Logout_Res value) {
        if (logoutResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          logoutResBuilder_.setMessage(value);
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <code>.SC_Logout_Res logoutRes = 5;</code>
       */
      public Builder setLogoutRes(
          Login.SC_Logout_Res.Builder builderForValue) {
        if (logoutResBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          logoutResBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <code>.SC_Logout_Res logoutRes = 5;</code>
       */
      public Builder mergeLogoutRes(Login.SC_Logout_Res value) {
        if (logoutResBuilder_ == null) {
          if (dataCase_ == 5 &&
              data_ != Login.SC_Logout_Res.getDefaultInstance()) {
            data_ = Login.SC_Logout_Res.newBuilder((Login.SC_Logout_Res) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 5) {
            logoutResBuilder_.mergeFrom(value);
          }
          logoutResBuilder_.setMessage(value);
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <code>.SC_Logout_Res logoutRes = 5;</code>
       */
      public Builder clearLogoutRes() {
        if (logoutResBuilder_ == null) {
          if (dataCase_ == 5) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 5) {
            dataCase_ = 0;
            data_ = null;
          }
          logoutResBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.SC_Logout_Res logoutRes = 5;</code>
       */
      public Login.SC_Logout_Res.Builder getLogoutResBuilder() {
        return getLogoutResFieldBuilder().getBuilder();
      }
      /**
       * <code>.SC_Logout_Res logoutRes = 5;</code>
       */
      public Login.SC_Logout_ResOrBuilder getLogoutResOrBuilder() {
        if ((dataCase_ == 5) && (logoutResBuilder_ != null)) {
          return logoutResBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 5) {
            return (Login.SC_Logout_Res) data_;
          }
          return Login.SC_Logout_Res.getDefaultInstance();
        }
      }
      /**
       * <code>.SC_Logout_Res logoutRes = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Login.SC_Logout_Res, Login.SC_Logout_Res.Builder, Login.SC_Logout_ResOrBuilder> 
          getLogoutResFieldBuilder() {
        if (logoutResBuilder_ == null) {
          if (!(dataCase_ == 5)) {
            data_ = Login.SC_Logout_Res.getDefaultInstance();
          }
          logoutResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Login.SC_Logout_Res, Login.SC_Logout_Res.Builder, Login.SC_Logout_ResOrBuilder>(
                  (Login.SC_Logout_Res) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 5;
        onChanged();;
        return logoutResBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NetMsg)
    }

    // @@protoc_insertion_point(class_scope:NetMsg)
    private static final AllMsg.NetMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AllMsg.NetMsg();
    }

    public static AllMsg.NetMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetMsg>
        PARSER = new com.google.protobuf.AbstractParser<NetMsg>() {
      @java.lang.Override
      public NetMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AllMsg.NetMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NetMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014AllMsg.proto\032\013Login.proto\"\256\001\n\006NetMsg\022\014" +
      "\n\004code\030\001 \001(\005\022!\n\010loginReq\030\002 \001(\0132\r.CS_Logi" +
      "n_ReqH\000\022!\n\010loginRes\030\003 \001(\0132\r.SC_Login_Res" +
      "H\000\022#\n\tlogoutReq\030\004 \001(\0132\016.CS_Logout_ReqH\000\022" +
      "#\n\tlogoutRes\030\005 \001(\0132\016.SC_Logout_ResH\000B\006\n\004" +
      "datab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Login.getDescriptor(),
        });
    internal_static_NetMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NetMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NetMsg_descriptor,
        new java.lang.String[] { "Code", "LoginReq", "LoginRes", "LogoutReq", "LogoutRes", "Data", });
    Login.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
